config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "auth/:provider/callback", to: "sessions#create", as: "google_auth"
  get "auth/failure", to: redirect("/")

  resources :users, except: :destroy do
    member do
      get :following, :followers
    end
  end
  resources :categories, only: :index
  resources :words, only: %i(index show)
  resources :lessons, except: %i(new edit)
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(destroy show index)
  resources :relationships, only: %i(create destroy)
  resources :activities, only: :destroy

  namespace :admin do
    root "static_pages#home"
    resources :words, except: :show
    resources :categories, except: :show
    resources :users, only: %i(index destroy)
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  before_create :build_questions
  before_update :update_status

  belongs_to :user
  belongs_to :category
  has_many :results, dependent: :destroy
  has_many :words, through: :results
  has_many :answers, through: :results
  accepts_nested_attributes_for :results

  enum status: {fresh: 0, in_progress: 1, finished: 2}

  validates :category, presence: true
  validates :user, presence: true
  validates :status, presence: true

  scope :desc, ->{order updated_at: :desc}

  paginates_per Settings.lesson.page_size
  max_paginates_per Settings.lesson.page_size

  def score
    if self.finished?
      "#{self.answers.correct_answers.size}/#{self.answers.size}"
    else
      "-"
    end
  end

  def action_name
    case status
    when :fresh.to_s
      I18n.t "lesson.index_view.start"
    when :in_progress.to_s
      I18n.t "lesson.index_view.continue"
    when :finished.to_s
      I18n.t "lesson.index_view.view"
    end
  end

  private

  def build_questions
    words = self.category.words.random_generate Settings.lesson.answers_num
    words.each{|word| self.results.build word_id: word.id}
  end

  def update_status
    answereds = results.select{|result| result.answer_id.present?}
    if answereds.size < words.size
      self.status = :in_progress
    else
      self.status = :finished
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :logged_in_user
  before_action :load_lesson, only: %i(show update destroy)
  before_action :correct_user, except: %i(index create)
  after_action :create_activity, only: %i(create update)

  def index
    @lessons = current_user.lessons.desc.page params[:page]
  end

  def show; end

  def create
    @lesson = Lesson.new lesson_params
    @description = t "lesson.create_activity",
      category: @lesson.category.name
    @action_type = :create_lesson

    if @lesson.save
      flash[:success] = t "lesson.create.success"
      redirect_to @lesson
    else
      flash[:danger] = t "lesson.create.failed"
      redirect_to lessons_path
    end
  end

  def update
    @lesson.update_attributes lesson_params
    if @lesson.valid?
      @lesson.save
      if @lesson.reload.finished?
        @description = t "lesson.finish_activity",
          category: @lesson.category.name
        @action_type = :finish_lesson
      end
      flash[:success] = t "lesson.update.success"
    else
      flash[:danger] = t "lesson.update.failed"
    end
    redirect_to lessons_path
  end

  def destroy
    if @lesson.destroy
      @message_type = Settings.message.success
      @message = t "lesson.destroy.success"
    else
      @message_type = Settings.message.danger
      @message = t "lesson.destroy.failed"
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def lesson_params
    params.require(:lesson).permit :category_id, :user_id, :status,
      results_attributes: [:id, :answer_id]
  end

  def load_lesson
    @lesson = Lesson.find_by id: params[:id]

    return if @lesson
    flash[:danger] = t "lesson.not_found"
    redirect_to lessons_path
  end

  def correct_user
    user = User.find_by id: @lesson.user_id

    redirect_to lessons_path unless user.is_user? current_user
  end
end

app/views/lessons/_correct_answer.html.erb
<% unless results_field.object.is_correct.nil? %>
  <% if results_field.object.is_correct %>
    <h6 class="answer-tag right-answer-tag">
      <%= t "lesson.show.right_answer" %>
    </h6>
  <% else %>
    <h6 class="answer-tag wrong-answer-tag ">
      <%= t "lesson.show.wrong_answer" %>
    </h6>
  <% end %>
<% end %>

app/views/lessons/_empty.html.erb
<tr>
  <td colspan="6" class="center">
    <%= t "lesson.index_view.empty" %>
  </td>
</tr>

app/views/lessons/_lesson.html.erb
<tr id="lesson-row-<%= lesson.id %>">
  <td><%= time_ago_in_words(lesson.created_at) %></td>
  <td><%= lesson.category.name %></td>
  <td><%= lesson.status %></td>
  <td><%= lesson.results.size %></td>
  <td><%= lesson.score %></td>
  <td>
    <%= link_to lesson.action_name, lesson,
      class: "waves-effect waves-light btn" %>
  </td>
  <td>
    <%= link_to t("lesson.index_view.delete"), lesson_path(lesson),
      method: :delete, data: {confirm: t("lesson.index_view.confirm_delete")},
      class: "btn waves-light waves-effect", remote: true %>
  </td>
</tr>

app/views/lessons/_result.html.erb
<ol>
  <%= f.fields_for :results do |results_field| %>
    <li>
      <div class="row question-row">
        <strong class="word-content">
          <%= results_field.object.word.content %>
        </strong>
      </div>
      <% results_field.object.word.answers.each do |answer| %>
        <div class="row answer-row">
          <div class="col s1 answer-radio">
            <%= results_field.radio_button :answer_id,
              answer.id, disabled: results_field.object.answer.present?,
              class: "result-radios" %>
          </div>
          <div class="col s5 answer-content answer-row">
            <%= answer.content %>
          </div>
        </div>
      <% end %>
      <% if f.object.finished? %>
        <%= render "correct_answer", results_field: results_field %>
      <% end %>
    </li>
  <% end %>
</ol>

app/views/lessons/destroy.js.erb
$('tr#lesson-row-<%= @lesson.id %>').fadeOut(500);
Materialize.toast('<%= @message %>', 4000, 'flash-<%= @message_type %>')

app/views/lessons/index.html.erb
<%= provide :title, t("lesson.index_view.title") %>
<div class="container">
  <div class="row center">
    <h4><%= t "lesson.index_view.title" %></h4>
  </div>
  <table class="striped" id="category-table">
    <div class="row">
      <thead>
        <tr>
          <th data-field="create_at">
            <%= t "lesson.index_view.created_at" %>
          </th>
          <th data-field="category">
            <%= t "lesson.index_view.category" %>
          </th>
          <th data-field="status">
            <%= t "lesson.index_view.status" %>
          </th>
          <th data-field="last_update">
            <%= t "lesson.index_view.num_words" %>
          </th>
          <th data-field="score">
            <%= t "lesson.index_view.score" %>
          </th>
          <th data-field="new">
            <%= link_to t("lesson.index_view.new"), categories_path,
              class: "waves-effect waves-light btn",
              id: "new-category-btn" %>
          </th>
        </tr>
      </thead>
      <tbody>
        <%= render(@lessons) || render("empty") %>
      </tbody>
    </div>
  </table>
  <div class="row center">
    <%= paginate @lessons, theme: "twitter-bootstrap-3" %>
  </div>
</div>

app/views/lessons/show.html.erb
<div class="container">
  <h4 class="center"><%= @lesson.category.name %></h4>
  <div class="divider"></div>
  <%= form_for @lesson, url: @lesson do |f| %>
    <%= render "result", f: f %>
    <% unless @lesson.finished? %>
      <div class="row center">
        <%= f.submit t("lesson.show.save"),
          class: "btn waves-effect waves-light" %>
      </div>
    <% end %>
  <% end %>
</div>