config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "auth/:provider/callback", to: "sessions#create", as: "google_auth"
  get "auth/failure", to: redirect("/")

  resources :users, except: :destroy do
    member do
      get :following, :followers
    end
  end
  resources :categories, only: :index
  resources :words, only: %i(index show)
  resources :lessons, except: %i(new edit)
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(destroy show index)
  resources :relationships, only: %i(create destroy)
  resources :activities, only: :destroy

  namespace :admin do
    root "static_pages#home"
    resources :words, except: :show
    resources :categories, except: :show
    resources :users, only: %i(index destroy)
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  validates :description, presence: true
  validates :action_type, presence: true

  enum action_type: {following: 0, unfollow: 1,
    create_lesson: 2, finish_lesson: 3}

  scope :of_user, ->user{where user_id: user.id}
  scope :desc, ->{order created_at: :desc}
  scope :feed, (lambda do |user_id, following_ids|
    where "user_id in (:following_ids) or user_id = :user_id",
      user_id: user_id, following_ids: following_ids
  end)
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :logged_in_user, :load_activity, :correct_user

  def destroy
    if @activity.destroy
      respond_to do |format|
        format.js
      end
    else
      flash[:danger] = t "activity.destroy.error"
      redirect_to current_user
    end
  end

  private

  def load_activity
    @activity = Activity.find_by id: params[:id]

    return if @activity
    flash[:danger] = t "activity.destroy.not_found"
    redirect_to current_user
  end

  def correct_user
    user = User.find_by id: @activity.user.id

    return if user.is_user? current_user
    flash[:danger] = t "activity.destroy.not_permit"
    redirect_to current_user
  end
end

app/views/activities/_activity.html.erb
<% @pronoun = current_user.is_user?(activity.user) ? "You" : activity.user.name %>
<tr class="activity-row z-depth-1" id="activity-row-<%= activity.id %>">
  <td>
    <%= content_tag :i, activity_icon(activity), class: "material-icons" %>
    <%= "#{@pronoun} #{activity.description}" %>
  </td>
  <td>
    <% if current_user.is_user? activity.user %>
      <%= link_to "X", activity_path(id: activity.id), method: :delete,
        data: {confirm: t("activity.destroy.confirm_delete")}, class: "btn",
        remote: true %>
    <% end %>
  </td>
</tr>

app/views/activities/destroy.js.erb
$('#activity-row-<%= @activity.id %>').fadeOut(300);